name = "working_actors"
version = "1.0.0"
licenses = ["MIT"]
description = "A library which spawns workers to run a function in parallel."
target = "erlang"

repository = { type = "github", user = "devries", repo = "working_actor" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
